### PR TITLE
update import with matchms

### PR DESCRIPTION
**Pull request by CunliangGeng**
To solve issue https://github.com/matchms/matchms/issues/30

### CODE REVIEW

**Review by fdiblen — CHANGES_REQUESTED** [review]
@CunliangGeng thank you for the changes.

I think it makes more sense to do the following for the imports:
instead of  `import matchms.ms_functions` use `from matchms import ms_functions`

**Comment by CunliangGeng** [comment]
You're right, thanks! Will change those.

**Comment by CunliangGeng** [comment]
Updated, ready for review.

**Comment by jspaaks** [comment]
Hi CunLiang:
sorry to interfere with your PR, but I think we should first refactor matchms itself a bit, and then once that has a more or less stable API, we can build on that. I've merged https://github.com/matchms/matchms/pull/47 as discussed during the standup, but that kind of cancels this PR.

How do you think we should proceed? Can I close/cancel this?

Thanks!
-Jurriaan

**Comment by CunliangGeng** [comment]
@jspaaks  OK, you can close and cancel this PR to keep things simple.

**Pull request closed without merging**
