### PR TITLE
New matchms

### PR DESCRIPTION
**Pull request by jspaaks**

### CODE REVIEW

**Review by HannoSpreeuw — COMMENTED** [review]
Nice

**Review by HannoSpreeuw — COMMENTED** [review]
Okay, this also covers #14

**Review by HannoSpreeuw — COMMENTED** [review]
Don't you need the `--editable` here?
So `- --editable=git+https://github.com/matchms/matchms.git@63-spectrum#egg=matchms`

**Review by HannoSpreeuw — COMMENTED** [review]
Why  does the `.git@63-spectrum` have to be added?
I thought it might work without that.
So just `--editable git+https://github.com/matchms/matchms#egg=matchms`

**Comment by jspaaks** [comment]
Re https://github.com/matchms/notebooks/pull/13#pullrequestreview-387352890:
- ``.git`` is just the url syntax (although it works without it as well)
- ``@63-spectrum`` was the branch I needed
- ``#egg`` does not work AFAICT
- I tried ``--editable``, but that seems to work for local install only, which kinda makes sense.

**Comment by jspaaks** [comment]
Hi Hanno, thanks for reviewing this PR. 

Sidenote: I think it good practice if people only delete branches that they themselves created.

**Comment by HannoSpreeuw** [comment]
Okay. I had deleted it because else it might be forgotten and we would have had a number of branches floating around in no time.
And making another issue assigning you to delete that branch would also invoke extra bureaucracy.
But perhaps you have a better suggestion.

**Comment by jspaaks** [comment]
> And making another issue assigning you to delete that branch would also invoke extra bureaucracy.
I agree that is not necessary.

The idea behind "only delete your own branches" is to give people a measure of control, which in my opinion is a necessity when multiple people are working together asynchronously and from physically separate locations.

**Comment by HannoSpreeuw** [comment]
Okay. Let's leave the branches alive, assuming the creator of the branch will delete it at the appropriate time.

**Pull request merged**
